# -*- coding: utf-8 -*-
"""Internship project 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fppWuhlEKPAFY030L9VF8upijOw3G4Vw

**Servo Prediction Using linear Regression**

**Objective**

Servo prediction using a linear regression typically involves creating a model to predict the behavior or performance of a servo motor based on certain input features

**Data Source**
"""

Ybi Foundation Github Csv File

"""**Import Library**"""

import pandas as pd
import numpy as np

"""**Import Data**"""

df=pd.read_csv(r'https://raw.githubusercontent.com/YBI-Foundation/Dataset/main/Servo%20Mechanism.csv')

"""**Describe Data**"""

df.describe()

"""**Data Preprocessing**"""

from re import T
df.replace({'Motor':{'A':0,'B':1,'C':2,'D':3,'E':4}},inplace=True)
df.replace({'Screw':{'A':0,'B':1,'C':2,'D':3,'E':4}},inplace=True)

"""**Define Target Variable (y) and Feature Variables (X)**"""

y=df['Class']

y.shape

x=df[['Motor','Screw','Pgain','Vgain']]

x.shape

"""**Train Test Split**"""

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3, random_state=2529)

x_train.shape,x_test.shape,y_train.shape,y_test.shape

"""**Modeling**"""

from sklearn.linear_model import LinearRegression
lr=LinearRegression()

lr.fit(x_train,y_train)

y_pred=lr.predict(x_test)

"""**Model Evaluation**"""

from sklearn.metrics import mean_squared_error, mean_absolute_error,r2_score

mean_squared_error(y_test,y_pred)

mean_absolute_error(y_test,y_pred)

r2_score(y_test,y_pred)

"""**Visualization**"""

from matplotlib import pyplot as plt
plt.scatter(y_test,y_pred)
plt.xlabel("Actual")
plt.ylabel("Prediction")
plt.title("Actual vs Prediction")
plt.show()

"""**Prediction**"""

x_new=df.sample(1)
x_new

x_new.shape

x_new=x_new.drop('Class',axis=1)
x_new

y_pred_new=lr.predict(x_new)
y_pred_new

"""**Explaination**

In this project we basically take Servo prediction scv file in which we will check the prediction of servo model using the Linear regression model so that we can have a comparisson between the actual one and the predicted one.Then making a visualization between the actual and predicted one to get the scatter graph and unterstanding the clear details.
"""